### ISSUE TITLE
Bringing it together

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#59]
How could you use alignment data (and samtools) in your own project?

Provide a least one example of what said code might look like.

**Comment by skreling** [comment]
For 1, I could use samtools to check the quality of the alignment and to visualize the aligned sample next to the reference genome with samtools view.

To check the quality readings of the alignment you can simply use:
`samtools view samplefile.sam | tr '\t' '\n' | head -n 11`
This will give use a simple overview of the entries in the SAM file and allow us to see it within a single view without it stretching off the width of the page. We can then look at the CIGAR string and MAPQ mapping quality sections to understand a bit more of about our alignments.

Secondly, once you get an indexed bam file, you can view it next to the reference genome using:
`samtools tview sample.bam reference.fasta`
You can also view a specific region by:
`samtools view -p 1:regionstart-regionend sample.bam \ reference.fasts`

**Comment by afcoyle** [comment]
One possible option is once I've filtered my sequences to only include those that originate from _Hematodinium_, I could use `samtools mpileup` to look for SNPs. Since to my knowledge we only have a transcriptome for _Hematodinium_, I might have to limit the examination to synonymous SNPs - without a genome, it seems impossible to differentiate between non-synonymous SNPS and different genes.

This could provide some indication of diversity between _Hematodinium_ strains within infected crabs. It would likely be quite low - all samples come from a small area in SE Alaska, and previous studies found little population structure for _Hematodinium_ on a global scale. But still could be worth investigating! I'm not sure if 

The command would look quite similar to the one from the other quiz - I just likely wouldn't specify region

```
samtools mpileup \
--no-BAQ \
--fasta-ref filename.fasta \
filename.bam
```

**Comment by jdduprey** [comment]
For metabarcoding my lab has compared sample ASVs against a database of known cytochrome oxidase I fragments. To supplement this assignment of taxa they have also used a custom database along with _bowtie2_. I think this pipeline would output alignment data that could be explored with Samtools. For example:

`samtools flags UNMAP`
This would indicate the bit flag for unmapped reads

`samtools view -F 4 alignment-file.bam | head -n 3`
This would select the unmapped reads from the alignment data file. In this case unmapped reads would be eDNA fragments with no assigned taxa.

**Comment by laurel-nave-powers** [comment]
I can use alignment data and samtools in my project to find SNPs using `samtools mpileup -no-BAQ -region ####-#### -fasta-ref name.fasta name.bam`. I can also use this to compare my reference sequence data to it. To be able to view the SNPs I can use `samtools tview`.

**Comment by meganewing** [comment]
Since I'm looking at changes in gene expression, I'll need to compare my experimental sequences to a control reference sequence and identify variants (once I get my sequences aligned, that is). But first I want to narrow my search down to sequences with qualities greater than 30:

`samtools view -q 30 -b AllQualities.bam > QualitySeqs.bam' Now all of my quality sequences are in a file. Then, I can look for variants within specific regions of my quality sequences with `samtools mpileup --no-BAQ --region <#:BP###-BP###> --fasta-ref <referenceGenome>.fasta sequenceVariants.bam'

**Comment by Brybrio** [comment]
I will attempt to find SNPs but my datasets are large, so I can subset my data to run initial trial processes more efficiently using `samtools index input.bam` and then `samtools view input.bam 1:###-###`. I can also filter my data specifying flags such as "PROPER-PAIR" or "PAIRED" in `samtools view -f 66 input.bam | head -n #`
